### ISSUE TITLE
Timetable Generation in GTFSM Failing

### ISSUE THREAD

**Issue by MarkTrillium** [Trillium-Solutions/gtfs-to-html-service#18]
@e-kane-optibus first noticed this issue when attempting to generate timetables for Placer County, but I tested other available exports and they all resulted in the same emailed error message seen below.

<img width="977" alt="Screen Shot 2023-02-16 at 11 46 20 AM" src="https://user-images.githubusercontent.com/52221348/219471281-4cfd5fa6-0484-43cc-a103-38febcb519c6.png">

I tested this in the following exports, all resulting in the same email.

- 21655, 21654, 21601, 21595, 21585

I am unable to modify the tags assigned to this ticket. Let me know if I should recreate this issue somewhere else or add any additional information.

**Comment by ekeaton** [comment]
@ungoldman i've tried a few things and the same error persists when trying to download timetables for Manager.

What I've done so far:

- First I ran the ansible playbook for `ansible-playbook playbooks/gtfstohtml/install_everything.yml` this is the playbook we ran to restart gtfstohtml last time when this error occurred. The playbook ran fine with zero failures and the normal output but I still received the same error via my email when I tried to download timetables from manager. 

- Second I went to the production version for gtfstohtml http://gtfstohtml.trilliumtransit.com/ to attempt to download timetables. The console for is usually a little busy here but it seems extra busy this time. What stood out to me with the POST and GET 400 bad requests for http://gtfstohtml.trilliumtransit.com/socket.io/etc etc. This might be an ssl cert issue. The production url is using http.

I went to the staging and dev sites both are using https and both are able to produce timetables just fine. https://development-gtfstohtml.trilliumtransit.com/ https://staging-gtfstohtml.trilliumtransit.com/

I looked in ansible it is hardcoded as http in a few places. Ex: https://github.com/Trillium-Solutions/ansible/blob/83a9bfe12aadbc7493a818222235a68c9ad9c77c/group_vars/gtfsmanager_production_realtime/all.yml#L14 so this might not be it! But this was my best observation!

**Comment by ungoldman** [comment]
Looking at error logs on the gtfstohtml server, there is something very odd happening there that suggests a deeper server issue.

```
error - uncaughtException: [  Error: The difference between the request time and the current time is too lar  ge.
] {
  message: 'The difference between the request time and the current time is too large.',
  code: 'RequestTimeTooSkewed',
  region: 'us-west-2',
  time: 2023-02-16T23:30:07.455Z,
  requestId: '78TQ151QPZS244CS',
  extendedRequestId: 'vjM1Qky8JBzewHfIB1wM579T0V4DiN5jRmf2JFLhUcQQgz/KWh9OnN7vUGaM/2CKgsFcmljG+JM=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 1.3771233601289623
}
[  Error: The difference between the request time and the current time is too lar  ge.
] {
  message: 'The difference between the request time and the current time is too large.',
  code: 'RequestTimeTooSkewed',
  region: 'us-west-2',
  time: 2023-02-16T23:30:28.339Z,
  requestId: '5332T5ZBC0KA7TH2',
  extendedRequestId: 'd4I/c8gwM8Ez4e0Ekj+opf/JHFGc31SiAS4MIFq391YVpzk9b7Zdy9MDYel215osetL/oTEtfdc=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 83.87070214485561
}
error - uncaughtException: [  Error: The difference between the request time and the current time is too lar  ge.
] {
  message: 'The difference between the request time and the current time is too large.',
  code: 'RequestTimeTooSkewed',
  region: 'us-west-2',
  time: 2023-02-16T23:30:28.339Z,
  requestId: '5332T5ZBC0KA7TH2',
  extendedRequestId: 'd4I/c8gwM8Ez4e0Ekj+opf/JHFGc31SiAS4MIFq391YVpzk9b7Zdy9MDYel215osetL/oTEtfdc=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 83.87070214485561
}
```

Many more of these. Found on gtfstohtml-b server, as gtfstohtml user, in file `/home/gtfstohtml/.pm2/logs/gtfs-to-html-service-error.log`

I'll try to figure this out again tomorrow.

**Comment by ungoldman** [comment]
At someone's suggestion on stackoverflow, tried comparing time between Amazon's servers and the gtfstohtml server to see if they're out of sync:

```
# Time from Amazon
$ curl http://s3.amazonaws.com -v

# Time on your local machine
$ date -u
```

Trying it out...

```
[gtfstohtml@gtfstohtml-b ~]$ curl http://s3.amazonaws.com -v
* Rebuilt URL to: http://s3.amazonaws.com/
*   Trying 54.231.160.128...
* TCP_NODELAY set
* Connected to s3.amazonaws.com (54.231.160.128) port 80 (#0)
> GET / HTTP/1.1
> Host: s3.amazonaws.com
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 307 Temporary Redirect
< x-amz-id-2: qDWywogG6ywn58K+EeTqpJSr4/014WsIrCnJGaSXFjWL8QiChCN9NgzkbM/GsV+3AcLbbauEEzw=
< x-amz-request-id: FT8H0V9NBK489ED6
< Date: Fri, 17 Feb 2023 04:18:08 GMT
< Location: https://aws.amazon.com/s3/
< Server: AmazonS3
< Content-Length: 0
<
* Connection #0 to host s3.amazonaws.com left intact
[gtfstohtml@gtfstohtml-b ~]$ date -u
Fri Feb 17 04:02:26 UTC 2023
```

Note there is a ~16 minute difference between what time these servers think it is. So our server's time is very off.

Going to try to figure out how to.. make the server... uh.. know what time it is... more better.

**Comment by ungoldman** [comment]
Time difference should be fixed now, not 100% sure this will solve the general GTFS2HTML issues but it sure would be cool if it did.

For future reference if anyone finds themself in my position trying to fix this:

1. `gtfstohtml-a` (and `-b`) server is running on `CentOS Stream release 8` (you can find this info by running `cat /etc/*-release`
2. There's a standard way to keep time up to date on linux servers using `ntp` and `ntpdate` (see https://stackoverflow.com/questions/49624148/how-to-fix-the-difference-between-the-request-time-and-the-current-time-is-too), but CentOS 8 deprecated that package, so you have to use something else called `chrony` (see https://www.tecmint.com/install-ntp-in-rhel-8/). So start by switching to root (`sudo su -`) then install `chrony` using the `dnf install chrony` command.
3. Once `chrony` is installed, you can start it using `systemctl`: `systemctl start chronyd`
4. Next give it half a minute to warm up, then check status. In this case it identified a system clock problem and fixed it:
  ```
  [root@gtfstohtml-b ~]# systemctl start chronyd
  [root@gtfstohtml-b ~]# systemctl status chronyd
  ● chronyd.service - NTP client/server
     Loaded: loaded (/usr/lib/systemd/system/chronyd.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-02-17 04:06:33 UTC; 15min ago
       Docs: man:chronyd(8)
             man:chrony.conf(5)
    Process: 2489664 ExecStartPost=/usr/libexec/chrony-helper update-daemon (code=exited, status=0/SUCCESS)
    Process: 2489660 ExecStart=/usr/sbin/chronyd $OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 2489662 (chronyd)
      Tasks: 1 (limit: 11395)
     Memory: 1.6M
     CGroup: /system.slice/chronyd.service
             └─2489662 /usr/sbin/chronyd
  
  Feb 17 04:06:33 gtfstohtml-b.trilliumtransit.com systemd[1]: Starting NTP client/server...
  Feb 17 04:06:33 gtfstohtml-b.trilliumtransit.com chronyd[2489662]: chronyd version 4.2 starting (+CMDMON +NTP +REFCLOCK +RTC >
  Feb 17 04:06:33 gtfstohtml-b.trilliumtransit.com chronyd[2489662]: Using right/UTC timezone to obtain leap second data
  Feb 17 04:06:33 gtfstohtml-b.trilliumtransit.com systemd[1]: Started NTP client/server.
  Feb 17 04:06:38 gtfstohtml-b.trilliumtransit.com chronyd[2489662]: Selected source 2001:1948:210:2::4 (2.centos.pool.ntp.org)
  Feb 17 04:06:38 gtfstohtml-b.trilliumtransit.com chronyd[2489662]: System clock wrong by 945.582985 seconds
  Feb 17 04:22:24 gtfstohtml-b.trilliumtransit.com chronyd[2489662]: System clock was stepped by 945.582985 seconds
  Feb 17 04:22:24 gtfstohtml-b.trilliumtransit.com chronyd[2489662]: System clock TAI offset set to 37 seconds
  ```
5. Last step, add it to system startup so the thing is always running and we never have to ever think about this again as long as we live: `systemctl enable chronyd`

Did this for a and b gtfstohtml servers, there are c and d ones, assuming these are Ed's staging/dev/emergency redundancy backup hotswap servers. I'll do it there for good measure too.

**Comment by ungoldman** [comment]
Those ones were off too, though D by the least (only 29 seconds off, still weird that they're all drifting off real time). My guess is some of this is a result of Ed's practice of having very long-lived servers, and cloning those servers to create new instances rather than building a server from a fresh image.

@ekeaton the 400 errors in the console are a different issue, there's something wrong with the socket server. I think we saw that last week and it didn't appear to have an impact on the service's main function, though it is weird. It's possible it requires a port to be open that Ed never opened. If it's still broken after all of the above I can dig more.

**Comment by ekeaton** [comment]
@ungoldman Thank you for looking into this! 

What you found is really interesting! But it's odd that downloading timetables works/worked on development which is using D when the time was off there maybe because it was only by 29 seconds?

Something else I notice in the console for both staging and dev is this:
![Screen Shot 2023-02-17 at 7 09 41 AM](https://user-images.githubusercontent.com/43942870/219691663-ee91c950-ec58-4313-b329-a007986d5548.png)

Which is not happening in production.

I tested running timetables again on http://gtfstohtml.trilliumtransit.com/ and hung for a long time and didn't produce anything. I tested running timetables in Manager and I received an email that my timetables were completed. So I'm not sure why there is a difference happening now between these two

**Comment by ekeaton** [comment]
@MarkTrillium I was able to run timetables for this feed in manager
![Screen Shot 2023-02-17 at 7 18 50 AM](https://user-images.githubusercontent.com/43942870/219693745-ef65f480-aebd-4281-8fed-f8e6912d005c.png)

Can you try as well on that feed and on a fresh export? Thank youuu!

**Comment by ungoldman** [comment]
re: your screenshot ("Something else I notice in the console for both staging and dev is this:")

it looks like the client is running in dev mode there. The presence of hot-dev-client.js suggests some kind of react-like hot reloading.

re:

> I tested running timetables again on http://gtfstohtml.trilliumtransit.com/ and hung for a long time and didn't produce anything. I tested running timetables in Manager and I received an email that my timetables were completed. So I'm not sure why there is a difference happening now between these two

It's possible the socket server, the thing that is erroring a lot, would update the interface to show that generation is complete, and is not doing that because it's broken.

You mentioned that you thought this was a SSL issue. I can try looking into that later today. You're welcome to try to debug that too.

**Comment by ungoldman** [comment]
Been digging into the SSL issue, there is definitely something weird going on there. There appear to be two different SSL certs getting delivered to the browser depending on timing. I think there's some deeper misconfiguration going on that's hard to trace. This might not be a bad opportunity to take a stab at deploying this service on a fresh server using newer infrastructure conventions rather than continuing to work with a lot of ed-isms no one fully understands anymore.

**Comment by ungoldman** [comment]
@MarkTrillium @e-kane-optibus has this problem been resolved for you?

**Comment by e-kane-optibus** [comment]
Yes, I have tested multiple exports and am able to successfully generate timetables on all

**Comment by ungoldman** [comment]
Thank you @e-kane-optibus! Closing this one.

@ekeaton We can investigate the SSL issue separately, I'll make a ticket on jira.
